

spring:
    application:
        name: businessdomain-boletavacacion
    liquibase:
        enabled: false
    profiles:
        active: domains
    # graphql:
    #     graphiql:
    #         enabled: true

    #     path: /graphql/
    devtools:
        restart:
            enabled: true
    main:
        allow-bean-definition-overriding: true
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: 8082
logging:
  level:
    '[org.springframework.web]': DEBUG
una:
    modulo: 53

