spring:
    application:
        name: businessdomain-funcionario
    datasource:
         hikari:
            connectionTimeout: 30000
            idleTimeout: 600000   
    graphql:
        graphiql:
            enabled: true

        path: /graphql/

        schema:
            introspection:
                enabled: true
    devtools:
        restart:
            enabled: true

    liquibase:
        enabled: false
    jpa:
        properties:
            hibernate:
                jdbc:
                    time-zone: UTC
        #         '[hibernate.format_sql]': true
        #         type: trace  
        # show-sql: true
        open-in-view: true
    mail:
        host: smtp.example.com
        port: 587
        username: your-email@example.com
        password: your-password
        properties:
            mail:
                smtp:
                auth: true
                starttls:
                    enable: true     
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
server:
  port: 8084
logging:
  level:
    '[org.springframework.web]': DEBUG
una:
    modulo: 37 
